#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : google-api-core
Version  : 1.22.0
Release  : 2
URL      : https://files.pythonhosted.org/packages/12/8e/eb5163a3a853fd85b9ed8c46038ca24c460ebb4e2a5cdc34a1d1415f1c77/google-api-core-1.22.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/12/8e/eb5163a3a853fd85b9ed8c46038ca24c460ebb4e2a5cdc34a1d1415f1c77/google-api-core-1.22.0.tar.gz
Summary  : Google API client core library
Group    : Development/Tools
License  : Apache-2.0
Requires: google-api-core-license = %{version}-%{release}
Requires: google-api-core-python = %{version}-%{release}
Requires: google-api-core-python3 = %{version}-%{release}
Requires: google-auth
Requires: grpcio
Requires: protobuf
Requires: pytz
Requires: requests
Requires: setuptools
Requires: six
BuildRequires : buildreq-distutils3
BuildRequires : google-auth
BuildRequires : grpcio
BuildRequires : protobuf
BuildRequires : pytz
BuildRequires : requests
BuildRequires : setuptools
BuildRequires : six

%description
========================================
        
        |pypi| |versions| 
        
        This library is not meant to stand-alone. Instead it defines
        common helpers used by all Google API clients. For more information, see the
        `documentation`_.

%package license
Summary: license components for the google-api-core package.
Group: Default

%description license
license components for the google-api-core package.


%package python
Summary: python components for the google-api-core package.
Group: Default
Requires: google-api-core-python3 = %{version}-%{release}

%description python
python components for the google-api-core package.


%package python3
Summary: python3 components for the google-api-core package.
Group: Default
Requires: python3-core
Provides: pypi(google_api_core)
Requires: pypi(google_auth)
Requires: pypi(googleapis_common_protos)
Requires: pypi(protobuf)
Requires: pypi(pytz)
Requires: pypi(requests)
Requires: pypi(setuptools)
Requires: pypi(six)

%description python3
python3 components for the google-api-core package.


%prep
%setup -q -n google-api-core-1.22.0
cd %{_builddir}/google-api-core-1.22.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1596512601
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/google-api-core
cp %{_builddir}/google-api-core-1.22.0/LICENSE %{buildroot}/usr/share/package-licenses/google-api-core/240c6d14564fceb27ae5dc4e51fc83055a8da35c
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/google-api-core/240c6d14564fceb27ae5dc4e51fc83055a8da35c

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
